export { default as StartupContainer } from './StartupContainer'
export { default as IndexLoginContainer } from './Login/Index'
export { default as IndexRegisterContainer } from './Register/Index'
export { default as IndexHomeContainer } from './MainHome/Index'
export { default as IndexUserProfileContainer } from './UserProfile/Index'
export { default as IndexRegisterCompanyUserContainer } from './RegisterCompanyUser/Index'
export { default as IndexEditUserContainer } from './EditProfile/Index'
export { default as IndexTutorialSlideContainer} from './TutorialSlide/Index'
export { default as IndexVirtualAccessContainer} from './VirtualCard/Index'
export { default as IndexSettingContainer} from './Setting/Index'
export { default as IndexVisitorContainer} from './Visitors/Index'
export { default as IndexCommunityContainer} from './Community/Index'